### ISSUE TITLE
Can't build project with target platform x64

### ISSUE THREAD

**Issue by haitc21** [Zerpico/libShout-csharp#2]
I run this code in Visual Studio and has error: "'An attempt was made to load a program with an incorrect format. (Exception from ".  I change property > build > target platform > x86 then ok. But I want build this project in x64. Could you help me?

**Comment by Zerpico** [comment]
Library [libshout-3.dll](https://github.com/Zerpico/libShout-csharp/blob/master/icecastSource/libshout-3.dll)  which I took from [icecast.org](https://icecast.org/download/) compiled only for x86. I tried to compile the library for the x64 platform from the source, but so far I have not been successful.
Perhaps you can find this library for x64 and dependencies from another place, or compile it yourself.
I'll try to do this later. And a better project would be nice to get better

**Comment by Zerpico** [comment]
Add x64/x86 support d467884
you can use this solution
